Layout/EndOfLine:
  EnforcedStyle: lf

Lint/ScriptPermission:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'biggles.gemspec'

Metrics/MethodLength:
  Max: 40

Metrics/AbcSize:
  Max: 25

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 35