Layout/EndOfLine:
  Enabled: false

Lint/ScriptPermission:
  Enabled: false

Metrics/BlockLength:
  Max: 40
  Exclude:
    - 'biggles.gemspec'
    - 'spec/*'

Metrics/MethodLength:
  Max: 40

Metrics/ClassLength:
  Max: 200

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 36

Style/SpecialGlobalVars:
  Enabled: false