sudo: false
language: ruby
rvm:
  - 2.3.3
before_install: gem install bundler -v 1.15.0

script:
  - bundle exec rubocop
  - bundle exec rake

addons:
  code_climate:
    repo_token: 88ef462c0744fee63435eb01f84d3b978210bf6de9782d781ee3304b3ae64b99

after_success:
  - bundle exec codeclimate-test-reporter