#!/usr/bin/env ruby

require 'biggles/cli'

main_command = ARGV.shift

if main_command.nil? || %w[-h --help].include?(main_command)
  puts 'Usage: biggles [command] <-c config_file>'
  puts
  puts '  start         - Start the Biggles job processor'
  puts '  create_schema - Create the Biggles database schema using your'
  puts '                  existing ActiveRecord configuration'
  puts '  remove_schema - Safely remove biggles database tables'
  puts '  list          - List all managed jobs and their status'
  puts
  exit 0
elsif %w[-v --version].include? main_command
  puts 'Biggles Job Processor'
  puts "  Version #{Biggles::VERSION}"
  exit 0
end

case main_command
when 'start'
  Biggles::CLI.start
when 'create_schema'
  Biggles::CLI.create_schema
when 'list'
  Biggles::CLI.list
else
  puts "Unknown Command #{main_command}. Try biggles --help"
  exit 1
end
