#!/usr/bin/env ruby

require 'biggles/cli'

def usage
  puts 'Usage: biggles [command] <-c config_file>'
  puts
  puts '  start         - Start the Biggles job processor'
  puts '  create_schema - Create the Biggles database schema using your'
  puts '                  existing ActiveRecord configuration'
  puts '  remove_schema - Safely remove biggles database tables'
  puts '  list          - List all managed jobs and their status'
  puts
  exit 0
end

main_command = ARGV.shift

if main_command.nil? || %w[-h --help].include?(main_command)
  usage
elsif %w[-v --version].include? main_command
  puts 'Biggles Job Processor'
  puts "  Version #{Biggles::VERSION}"
  exit 0
end

loop do
  switch = ARGV.shift
  case switch
  when nil
    break
  when '-c'
    @config_file = ARGV.shift
    unless File.exist?(@config_file)
      STDERR.puts "Configuration file #{@config_file} not found."
      exit 1
    end
  else
    STDERR.puts "Unknown command line option #{switch}"
    usage
    exit 1
  end
end

case main_command
when 'start'
  Biggles::CLI.start
when 'create_schema'
  Biggles::CLI.schema(:up)
when 'remove_schema'
  Biggles::CLI.schema(:down)
when 'list'
  Biggles::CLI.list
else
  STDERR.puts "Unknown command #{main_command}"
  usage
  exit 1
end
